// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace LB3
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"country")]
            public string Country { get; set; }

            [ColumnName(@"description")]
            public string Description { get; set; }

            [ColumnName(@"designation")]
            public string Designation { get; set; }

            [ColumnName(@"points")]
            public float Points { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"province")]
            public string Province { get; set; }

            [ColumnName(@"region_1")]
            public string Region_1 { get; set; }

            [ColumnName(@"region_2")]
            public string Region_2 { get; set; }

            [ColumnName(@"variety")]
            public string Variety { get; set; }

            [ColumnName(@"winery")]
            public string Winery { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"country")]
            public float[] Country { get; set; }

            [ColumnName(@"description")]
            public string Description { get; set; }

            [ColumnName(@"designation")]
            public uint Designation { get; set; }

            [ColumnName(@"points")]
            public float Points { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"province")]
            public string Province { get; set; }

            [ColumnName(@"region_1")]
            public string Region_1 { get; set; }

            [ColumnName(@"region_2")]
            public string Region_2 { get; set; }

            [ColumnName(@"variety")]
            public string Variety { get; set; }

            [ColumnName(@"winery")]
            public string Winery { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
